Repository gardener/network-problem-detector, pull requests merged in 2023-01, with the labels that each got.

#30 Liveness probe for HTTP port
  pkg/agent/server.go
  pkg/deploy/agent.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#33 Update builder image to `golang:1.19.5`
  .ci/pipeline_definitions
  Dockerfile
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#34 Support for optional node sampling to reduce number of metrics
  hack/network-problem-detector-traffic.xlsx
  pkg/agent/runners/parser.go
  pkg/agent/runners/parser_test.go
  pkg/agent/server.go
  pkg/common/config/agent.go
  pkg/common/config/config_suite_test.go
  pkg/common/config/endpoint.go
  pkg/common/config/sample.go
  pkg/common/config/sample_test.go
  pkg/deploy/agent.go
  pkg/deploy/clusterconfig.go
  pkg/deploy/command.go
Labels: reviewed/lgtm, needs/ok-to-test, size/l

#35 Ensure agent checks own node
  pkg/agent/aggregation/aggregator.go
  pkg/agent/aggregation/k8s_exporter.go
  pkg/agent/runners/internaljob.go
  pkg/agent/runners/robinround.go
  pkg/agent/runners/utils.go
  pkg/agent/server.go
  pkg/common/config/sample.go
  pkg/common/config/sample_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#36 Node conditions should not be set on check failures of few other nodes
  pkg/agent/aggregation/aggregator.go
  pkg/agent/aggregation/k8s_exporter.go
  pkg/agent/runners/internaljob.go
  pkg/agent/runners/parser.go
  pkg/agent/runners/parser_test.go
  pkg/agent/server.go
  pkg/common/config/agent.go
  pkg/common/utils.go
  pkg/deploy/agent.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#37 Exclude not-running and "ghost" agent pods from cluster-config.
  pkg/deploy/clusterconfig.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#38 Add CVE categorisation.
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
