Repository gardener/network-problem-detector, pull requests merged in 2024-10, with the labels that each got.

#75 Introduce gosec for Static Application Security Testing (SAST)
  .gitignore
  .golangci.yaml
  Makefile
  hack/sast.sh
  hack/tools/install-gosec.sh
  hack/tools/tools.mk
  pkg/agent/aggregation/aggregator.go
  pkg/agent/db/writer2.go
  pkg/agent/runners/checkhttpsget.go
  pkg/agent/runners/checktcpport.go
  pkg/agent/server.go
  pkg/aggregate/command.go
  pkg/collect/command.go
  pkg/collect/command_run.go
  pkg/common/config/sample.go
  pkg/common/config/utils.go
  pkg/list/command.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#76 support also checks for ipv6 endpoints
  pkg/agent/runners/checktcpport.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, area/ipcei

#77 Use filepath.Clean to get rid of gosec G304
  pkg/agent/aggregation/aggregator.go
  pkg/agent/db/writer2.go
  pkg/collect/command.go
  pkg/collect/command_run.go
  pkg/common/config/utils.go
Labels: needs/ok-to-test, needs/review, size/xs

#78 Delete corrupt current record file on restart.
  pkg/agent/db/writer2.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
