Repository gardener/network-problem-detector, pull requests merged in 2025-05, with the labels that each got.

#96 fix(deploy): trim all newlines from defaultRepository
  pkg/deploy/agent.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#93 Add additional jobs for IPv6 to support dual-stack cluster.
  README.md
  pkg/agent/runners/checktcpport.go
  pkg/common/config/endpoint.go
  pkg/common/config/sample.go
  pkg/common/constant.go
  pkg/deploy/agent.go
  pkg/deploy/clusterconfig.go
  pkg/deploy/clusterconfig_test.go
  pkg/deploy/command.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#97 fix(controller): ensure `shootInfo` is nil if `Get` errored with `404`
  pkg/controller/watch.go
Labels: needs/ok-to-test, needs/changes, needs/second-opinion, size/xs
